name = "LowRankOpt"
uuid = "607ca3ad-272e-43c8-bcbe-fc71b56c935c"
authors = ["Beno√Æt Legat <benoit.legat@gmail.com>"]
version = "0.1.0"

[deps]
MathOptInterface = "b8f27783-ece8-5eb3-8dc8-9495eed66fee"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
MathOptInterface = "1.34.0"
Test = "<0.0.1, 1.10"
julia = "1.10"
